### PR TITLE
Mouse tracking

### PR DESCRIPTION
**Pull request by kubaroth**
Enables mouse tracking and button-down functionality. Included paint.go example in the _demo folder.

### CODE REVIEW

**Comment by nsf** [comment]
Will take a look at it in few days. Happy new year.

**Comment by nsf** [comment]
Sorry it took so long. I don't like the overall quality of the patch (for example you leave commented out code everywhere) which means it requires a lot of modifcations on my side. And I need to test it on all terminals. Have you tested it on anything except xterm? And I need to implement the functionality on windows. And I'm not sure I like all these Ctrl/Alt modifier constants, the way you present them, what about Ctrl+Alt?

It doesn't give me an impression of a well thought implementation, I'm not willing to accept anything else.

Sorry, will keep it hanging open here for now.

**Comment by kubaroth** [comment]
Thanks for looking into this.
I can remove comments (which btw. I thought would give a better picture where I was coming from) and limit the added key constants entries just to MouseRelease and MouseDown to keep changes minimal.
I'm not familiar with the windows terminal, so any suggestions how would you approach implementation there are appreciated? I believe you'd like to stick with golang only?
I agree lack of compatibility between xterm and other terminals may by the biggest problem in this case.
Thanks

**Comment by nsf** [comment]
I'll implement it all next weekend myself.

**Comment by nsf** [comment]
So, I've implemented it here for terminals: https://github.com/nsf/termbox-go/commit/4aa457c414d0392fb8981c

Will be working on windows version now.

The semantics is the following: You can press left, middle, right mouse buttons and mouse wheel. For LMB, MMB and RMB when you release it, MouseRelease event is reported. Because that's a bare minimum which is provided by old X10 protocol.

Mouse dragging is also supported, ModMotion modifier is set on Event.Mod field when you drag a mouse with a button pressed.

Technically I use extended xterm mode and on xterm it is possible to see which button was released, but many other terminals don't support it, for example urxvt doesn't report that and I tried tmux which doesn't even support any of the extended modes it reports back with X10 stuff.

Feel free to try _demos/raw_input.go to see which terminals return what.

And I've added _demos/paint.go, a slightly advanced version of a paint demo you've made. In addition to painting you can select active color/rune there. ESC for exit.

**Comment by nsf** [comment]
Update: actually tmux can do xterm extended mode, but only when you run tmux under xterm, doesn't do so under urxvt for some reason. Anyways, using X10, xterm ext and urxvt ext modes all at once seems like it provides decent compatibility with most terminals.

**Comment by nsf** [comment]
Implemented on windows:

tbmousewin

**Comment by kybin** [comment]
great picture, by the way :)

**Comment by nsf** [comment]
> great picture, by the way :)

:grin:

**Comment by kubaroth** [comment]
This looks great! Thanks so much. I think we can close this one.

**Pull request closed without merging**
