### PR TITLE
CJK works just fine on windows

### PR DESCRIPTION
**Pull request by doun**
And if CJK is not to be supported, it's better to throw an error or so. As a newbie, I spent an hour to find out the reason why CJK chars are BLANK.

### CODE REVIEW

**Comment by nsf** [comment]
The problem is that it doesn't work on my machine. It seems that whether CJK works or not is dependent on windows version. I'll take a look again and will apply the pull request, but how can I support the feature if I can't test it.

**Comment by doun** [comment]
It works now

**Comment by nsf** [comment]
Why closing the pull request? I wanted to take a look at it today in few hours. :)

You've made a bit of mess in commits ("i think it's ok" is not a good commit comment), so maybe I'll recommit the changes.

**Comment by doun** [comment]
I closed it because of these mess commit messages~~.
I'd like to create another PR if needed.

**Comment by nsf** [comment]
Well, if you want to, sure, redo the commits.

**Comment by nsf** [comment]
Oh, also, can you show me screenshots of a working _demos/output.go? Just to be sure I have something to compare with when checking out the code.

**Comment by doun** [comment]
@nsf, please check http://www.cnblogs.com/doun/p/4300437.html

for the screenshot

**Comment by nsf** [comment]
Thanks, looks correct indeed.

**Comment by nsf** [comment]
So, should I wait a new pull request from you or should I apply all the patches myself? Because you've closed this one and.. it's 2 days already.

**Comment by mattn** [comment]
@doun Why you don't send PR? If you allow, I'll send PR of your changes. :)

**Comment by nsf** [comment]
Do that, I'm sure he doesn't mind.

**Pull request closed without merging**
