### PR TITLE
Fix CJK widths

### PR DESCRIPTION
**Pull request by mattn**
This runs on cp866

### CODE REVIEW

**Comment by mattn** [comment]
Ooops. This still have problem.

**Comment by nsf** [comment]
Let's just leave it as is. Because it's fine for me. If you're using the right CP, it works, if not - then it's your problem. To me it seems there are people who are interested in CJK, which are using the right CP and everyone else, which do have their own CP. So, it kinda works.

**Comment by mattn** [comment]
Ah,

**Comment by mattn** [comment]
Sorry, I'll look into it again

**Pull request closed without merging**
