### PR TITLE
Fix cjk width

### PR DESCRIPTION
**Pull request by mattn**
Related issue #69 #72

### CODE REVIEW

**Comment by mattn** [comment]
[termui](https://github.com/gizak/termui)



works fine

**Comment by mattn** [comment]
[peco](https://github.com/peco/peco)

http://go-gyazo.appspot.com/d0c8c3dcac4f657a.png

works fine too

**Comment by mattn** [comment]
@nsf do you know the another famous product which should be check this change?

**Comment by nsf** [comment]
Our own _demos/output.go has some cjk characters in it. But no, have no idea.

**Comment by mattn** [comment]
Is this your expected?

**Comment by nsf** [comment]
Yes, looks good. But that's how it looks on my machine (that's what I meant by "it doesn't work for me"):

termboxcjk

**Comment by mattn** [comment]
What is your code page?

**Comment by nsf** [comment]
What do you mean code page? It's a typical windows setup with russian/english locales.

**Comment by mattn** [comment]
please type `chcp` on cmd.exe

**Comment by nsf** [comment]
Says 866.

**Comment by mattn** [comment]
@nsf because cell width is hard-coded as 2. https://github.com/nsf/termbox-go/blob/master/_demos/output.go#L57

**Comment by nsf** [comment]
@mattn But what does it change? I mean when font doesn't support CJK runes things get broken?

**Comment by mattn** [comment]
ok, I could reproduce your problem.

```
chcp 866
```


I'll look into it.

**Comment by mattn** [comment]
It seems that prepare_diff_messages should be fixed I think.

**Comment by mattn** [comment]
About making diffs, diffs should be separated per lines. because columns is not width in CJK.

```
diff --git a/termbox_windows.go b/termbox_windows.go
index 62ac3fa..45b69e5 100644
--- a/termbox_windows.go
+++ b/termbox_windows.go
@@ -456,6 +456,14 @@ const (
 	surr_self        = 0x10000
 )
 
+func rune_width(r rune) int {
+	w := runewidth.RuneWidth(r)
+	if w == 0 || w == 2 && runewidth.IsAmbiguousWidth(r) {
+		w = 1
+	}
+	return w
+}
+
 func append_diff_line(y int) int {
 	n := 0
 	for x := 0; x < front_buffer.width; {
@@ -463,16 +471,10 @@ func append_diff_line(y int) int {
 		back := &back_buffer.cells[cell_offset]
 		front := &front_buffer.cells[cell_offset]
 		attr, char := cell_to_char_info(*back)
-		w := runewidth.RuneWidth(back.Ch)
-		if w == 0 {
-			w = 1
-		}
-		if w == 0 || w == 2 && runewidth.IsAmbiguousWidth(back.Ch) {
-			w = 1
-		}
 		charbuf = append(charbuf, char_info{attr: attr, char: char[0]})
-		n++
 		*front = *back
+		n++
+		w := rune_width(back.Ch)
 		x += w
 	}
 	return n
@@ -498,25 +500,17 @@ func prepare_diff_messages() {
 				break
 			}
 		}
-		if same && diff.lines > 0 {
-			diffbuf = append(diffbuf, diff)
-			diff = diff_msg{}
-		}
 		if !same {
+			diff = diff_msg{}
 			beg := len(charbuf)
 			end := beg + append_diff_line(y)
-			if diff.lines == 0 {
-				diff.pos = short(y)
-				gbeg = beg
-			}
-			diff.lines++
+			diff.lines = 1
+			diff.pos = short(y)
+			gbeg = beg
 			diff.chars = charbuf[gbeg:end]
+			diffbuf = append(diffbuf, diff)
 		}
 	}
-	if diff.lines > 0 {
-		diffbuf = append(diffbuf, diff)
-		diff = diff_msg{}
-	}
 }
 
 func cell_to_char_info(c Cell) (attr word, wc [2]wchar) {
```

But it seems to be problem in another part.

**Comment by pomutemu** [comment]
```
Microsoft Windows [Version 10.0.10074]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Windows\system32>chcp 932
現在のコード ページ: 932
```

[Gyazo](http://gyazo.com/102f83ec87e3d5771f2300405a139b6e)

**Comment by mattn** [comment]
Probably your font is not rasterfont. right?

**Comment by pomutemu** [comment]
You are right.
Thanks!

**Pull request merged**
