### PR TITLE
Fix rendering of multi-byte strings

### PR DESCRIPTION
**Pull request by mattn**
https://docs.microsoft.com/en-us/windows/console/reading-and-writing-blocks-of-characters-and-attributes

https://docs.microsoft.com/en-us/windows/console/char-info-str

In latest cmd.exe, multi-byte strings must be handled with attributes of COMMON_LVB_XXX.

### CODE REVIEW

**Comment by mattn** [comment]
This fix issue that Windows Terminal does not work correctly with multi-byte strings.

**Comment by scrouthtv** [comment]
First of all thanks for the PR!
I have some questions:
I suppose an example for multibyte characters are chinese characters, e. g. `在`.
I am testing this character using `editbox.go` provided in the `_demos` folder.

Current status with `nsf/master` is that multibyte characters overdraw some things:
editboxmaster

Now using your fix, the same scenario using Windows 10 v19041 looks like this:
editboxfix

Three things I've noticed:
 1. The bar at the end moves one character to the right
 2. There is a space after the multibyte character
 3. The cursor is off by one (I can't go further to the right, and deleting deletes the character right off the cursor, not left of it)

Now regarding 2. I thougt there is an issue with multibyte characters and my font, however this is the very same window but vim open and the character renders properly:
image

Do you have any clue how to further fix these?
I checked `editbox.go` and 
 - The bar at the end is drawn at an arbitrary position using `termbox.SetCell` (see lines 245 and 254)
 - The character width is calculated using runewidth.RuneWidth (see line 13)

I've run all my tests in the new Windows Terminal, inserting multi-byte characters also does *not* work in a plain cmd.exe for me:
editboxplaincmd
Notice how I first successfully insert the chinese character in the Windows Terminal, and then run the very same test in a plain cmd.exe but I can't insert the character using Insert.
I think this one is an issue with `cmd.exe` that we can't fix, since I can also not insert a multibyte character in the plain cmd prompt using Insert. I just noticed that raw_input.go is broken on Windows, so I can't test that.

I also would like to know whether this fix is backwards compatible with anything older than Windows 10 (7, 8, ...)?

Thank you for your patience and have a nice day!

**Comment by mattn** [comment]
What is your console code page? editor.go should replace bars with ascii-borders if using CJK.

image

**Comment by scrouthtv** [comment]
My Windows's language is set to English...

**Comment by mattn** [comment]
It's an East Asian Ambiguous Width. The width of bar might be changed with locales you are using. Also  the width is not compatible on Windows and wcwidth(2). go-runewidth follows wcwidth(2).

**Comment by mattn** [comment]
Anyway, this is not related on this pull-request.

**Comment by scrouthtv** [comment]
Thank you. But what is about the cursor issue and the spacing after the cjk character (both in the second gif)? Am I the only one having it? Your screenshot doesn't look like it.

**Comment by mattn** [comment]
What value do you get with `chcp` on cmd.exe ?

**Comment by scrouthtv** [comment]
Active codepage: 437

**Comment by mattn** [comment]
Could you please try this code with `go run` ?

```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println(`
┌──┐
│在│
└──┘
`)
}
```

image

**Comment by mattn** [comment]
This is result on Linux (mintty terminal)

image

**Comment by scrouthtv** [comment]
image
PowerShell in the new Windows Terminal

**Comment by scrouthtv** [comment]
image
cmd.exe in the old conhost

**Comment by mattn** [comment]
@nsf the issue @scrouthtv mentioned is another issue that must be fixed. So let's merge this?

**Pull request merged**
