### PR TITLE
CJK works just fine on windows

### PR DESCRIPTION
**Pull request by mattn**
#69

### CODE REVIEW

**Comment by nsf** [comment]
Seriously? I was bashing the guy for commit messages like these: "i think it's ok" and wanted him to redo the commits and make another pull request. And you're just doing the same. Is it hard to rebase/squash all the commits into a single one with a nice comment? "Fix CJK on windows" or something. Thank you in advance.

**Comment by mattn** [comment]
Ah, sorry. I didn't understand your opinions about the PR. So I'll update this PR with good commit message.

**Comment by mattn** [comment]
I'm looking into this.

https://github.com/nsf/termbox-go/blob/master/termbox_windows.go#L470-L476

Why this part is needed?

**Comment by mattn** [comment]
It should be below?

```diff
diff --git a/termbox_windows.go b/termbox_windows.go
index fb20a16..2d2d305 100644
--- a/termbox_windows.go
+++ b/termbox_windows.go
@@ -467,7 +467,7 @@ func append_diff_line(y int) int {
 		if w == 0 {
 			w = 1
 		}
-		if w == 2 {
+		if x+w >= front_buffer.width {
 			// not enough space for a 2-cells rune,
 			// let's just put a space in there
 			front.Ch = ' '
```

**Comment by nsf** [comment]
@mattn That part was temporary inserted by me, because on my machine I couldn't make CJK work. No matter what I do. You can replace it with whatever works for you, as long as doesn't break non-wide characters.

**Comment by mattn** [comment]
>  because on my machine I couldn't make CJK work.

How couldn't work? I'm thinking the behavior is not shared. And I'm thinking this should be solved.

**Comment by nsf** [comment]
I think windows highly depends on selected language. If it was installed with CJK support then it does things differently. Not sure about that.

**Pull request closed without merging**
